[Paths]
# Ruta al archivo Excel maestro que se usará como plantilla.
source_excel_path = C:\Users\PC\Downloads\Control_PQR_JSUARCAR_EMTELCO - AUTOMATIZADA- JSUARCAR.xlsx

# Directorio donde se guardarán las copias de trabajo del archivo Excel.
dest_dir = C:\Users\PC\Downloads\